name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via NPM) using bun or npm command and cache them.'
inputs:
  npm:
    description: 'Use npm command to install dependencies'
    required: false
    default: 'false'
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.npm == 'true' && inputs.caching == 'true'
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Cache dependencies
      if: inputs.npm == 'false' && inputs.caching == 'true'
      id: cache-bun
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/bun.lockb') }}

    - name: Install dependencies
      id: install-npm
      if: inputs.npm == 'true' && (steps.cache-npm.outputs.cache-hit != 'true' || inputs.caching != 'true')
      run: |
        npm ci
      shell: bash

    - name: Install dependencies
      id: install-bun
      if: inputs.npm == 'false' && (steps.cache-bun.outputs.cache-hit != 'true' || inputs.caching != 'true')
      run: |
        bun install --frozen-lockfile
      shell: bash
