name: Deploy to Storybook Repo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
      - 'tests/**'
      - 'src/__tests__/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Get & cache dependencies
        uses: ./.github/actions/get-dependencies

      - name: Build
        run: |
          bun build-storybook

      - name: Checkout Another Repository
        uses: actions/checkout@v4
        with:
          repository: ngphanducthinh/7pmlabs-design-system # replace with the actual repository URL
          token: ${{ secrets.DESIGN_SYSTEM_STORYBOOK }}
          path: 7pmlabs-design-system # replace with the desired path in your workspace

      - name: Copy Built Files
        run: |
          cp -R storybook-static/* 7pmlabs-design-system/

      - name: Commit and Push Changes to Another Repository
        run: |
          cd 7pmlabs-design-system
          git config user.email "ngphanducthinh@gmail.com"
          git config user.name "Thinh Nguyen"
          git add .
          git commit -m "Update built files"
          git push
