name: Publish NPM Patch Beta Version

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Determine Current Version
        id: get-version
        run: echo "current_version=$(npm show @7pmlabs/design-system version)" >> $GITHUB_OUTPUT

      - name: Bump Patch Version
        id: bump-version
        run: |
          current_version="${{ steps.get-version.outputs.current_version }}"
          echo "$current_version"
          value_3=$(echo "$current_version" | awk -F. '{print $3}')
          if [ "$value_3" -ge 1 ]; then
          patch_beta_version="${current_version}.${value_3}-beta.$(( ${current_version##*.} + 1 ))"
          else
          patch_beta_version="${current_version}.$(( ${current_version##*.} + 1 ))-beta.$(( ${current_version##*.} + 1 ))"
          fi
          echo "new_version=$patch_beta_version" >> $GITHUB_OUTPUT

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Set your npm authentication token as a secret
        run: |
          echo ${{ steps.bump-version.outputs.new_version }}